apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secrets
  namespace: petclinic
type: Opaque
stringData:
  url: jdbc:mysql://petclinic-db.xxxxxxxxxxxx.region.rds.amazonaws.com:3306/petclinic
  username: petclinic
  password: YOUR_DB_PASSWORD
